# Generated by Django 4.2.7 on 2023-11-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textInput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(default='Not Analyzed', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dweet',
            name='sentiment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textInput.sentiment'),
        ),
    ]
