# Generated by Django 4.2.7 on 2023-11-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textInput', '0002_sentiment_dweet_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textInput.sentiment'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
    ]
